markdown: kramdown

exclude:
  - .editorconfig
  - .gitignore
  - README.md
  - Gemfile*
  - vendor
  - RoboFile.php
  - LICENSE
  - composer.*
collections:
  problems:
    output: true
    permalink: /problems/:path.html
defaults:
  - scope:
      type: problems
    values:
      layout: problem
